import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Banner } from '@/components/Banner';
import { About } from '@/components/About';
import { Services } from '@/components/Services';
import { Cta } from '@/components/Cta';
import { Commitee } from '@/components/Commitee';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Encon - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <About/>
      <Services/>
      <Cta/>
      <Commitee/>
    </>
  )
}
